import { Component, OnInit, EventEmitter, Output, Inject } from '@angular/core';
import { MAT_DIALOG_DATA } from '@angular/material/dialog';

@Component({
  template: "\n<h1 mat-dialog-title>How to use the: {{data.subtitle}}</h1>\n<div style=\"margin: 10px; height: 450px; overflow-y: scroll; \">\n  <div style=\"text-align: center; font-weight: bold; \">\n    OVERVIEW\n  </div>\n  <div>\n    The Notification feature is a type of messaging system. The system will send and receive notifications, but is not limited to text. It is also possible to send and receive objects and collection.\n  </div>\n  <div style=\"text-align: center; font-weight: bold; \">\n    Steps to Send a Notification\n  </div>\n  <div>\n    1)	Register the channel by entering the channel name in the \"Channel Name\" textbox.\n    <br />\n    &nbsp;&nbsp;&nbsp;&nbsp;The channel name can be any name you choose\n    <br />\n    2)	Click the \"Register\" button\n    <br />\n    3)	Enter text in the \"Transmit Message(s)\" textbox\n    <br />\n    4)	Click the send button\n  </div>\n  <div style=\"text-align: center; font-weight: bold; \">\n    Steps to Receive a Notification\n  </div>\n  <div>\n    1)	Register the channel, as you did in step 1 above\n    <br />\n    2)	From the \"Receiving Subscription(s)\" list box, select which channel(s) that you want\n    <br />\n    &nbsp;&nbsp;&nbsp;&nbsp;to receive notifications from. This can be your own channel\n    <br />\n    3)	Now when the channels that you have subscribed to send notifications, you will see the channel name along with the message, in the \"Received Message(s)\" textbox\n  </div>\n  <br />\n  <div style=\"text-align: center; font-weight: bold; \">\n    Composing a Text Message\n  </div>\n  <div>\n    You can enter text without the keyboard by using the \"Speech to Text\" converter.\n    To the right of the \"Transmit Message(s)\" textbox is a microphone icon. Click this icon and begin speaking. Your speech will be converted to text.\n  </div>\n  <br />\n  <div style=\"text-align: center; font-weight: bold; \">\n    Voice Activated Commands\n  </div>\n  <div>\n    You can activate commands without the keyboard or mouse by using the \"Speech to Text\" converter. Click the microphone and begin speaking. Your voice commands will initiate the notification commands.\n    <br /><br />\n    Here is an example registering a channel named \"Jupiter Station\".\n    <br />\n    1)	Click on the microphone icon\n    <br />\n    2)	Speak: Computer, register channel \"Jupiter Station\"\n  </div>\n  <br />\n  <div style=\"text-align: center; font-weight: bold; \">\n    Other Voice Activate Commands\n  </div>\n  <div>\n    Computer, subscribe to channel \"Jupiter Station\"\n    <br />\n    Computer, unregister channel\n    <br />\n    Computer, send message\n    <br />\n    Computer, clear text\n    <br />\n  </div>\n</div>\n"/* this was squashed */
})
export class NotificationHelpDialog {
  constructor(@Inject(MAT_DIALOG_DATA) public data: {}) { }
}
